name: Daily grouping parquet files

on:
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run grouping parquet files
        env:
          # DigitalOcean Spaces
          SPACES_ENDPOINT: ${{ secrets.SPACES_ENDPOINT }} #
          SPACES_BUCKET: ${{ secrets.SPACES_BUCKET }} #
          SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }} #
          SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }} #
        run: |
          python scripts/parquet_grouping.py
